pushing rough draft to master
pcgeek2301/csc205 pull request #5
Opened 2021-03-26 20:49 UTC by pcgeek2301

Finished project and wanted to have it reviewed

2021-03-26 22:11 UTC, imapcgeek requested changes
We should discuss the static methods in Company and how it can be changed to now require them, which I consider to be an anti-pattern.

2021-03-26 22:11 UTC, imapcgeek commented on AdministrativeAssistant.java
> +    public void setHours(int hours) {
It is common convention to keep the "getter" and "setter" together. This is because they logically represent a "property" of the class.

2021-03-26 22:11 UTC, imapcgeek commented on AdministrativeAssistant.java
> +    }
Why do you need this method if you already have a method setHours()?

2021-03-26 22:11 UTC, imapcgeek commented on AdministrativeAssistant.java
> +    }
I would change the name of this to something else like "payday()" or something other than "get..." because you aren't actually "getting" anything. It returns void.

2021-03-26 22:11 UTC, imapcgeek commented on Company.java
> +    AdministrativeAssistant[] hourEmployees = new AdministrativeAssistant[MAX];
I recommend renaming the variable to something like "administrativeAssistants".

2021-03-26 22:11 UTC, imapcgeek commented on Company.java
> +            userChoice = userChoice.toLowerCase();
You might consider combining this into a chained call like:
userChoice = scnr.nextLine().toLowerCase();

2021-03-26 22:11 UTC, imapcgeek commented on Company.java
> +    public static void PromptUserForNewEmployee(Company comp, Scanner scnr) {
instead of making these kinds of methods static and requiring you to pass in the company, I'd recommend  removing the static and calling theCompany.PromptUserForNewEmployee(). Also, I'd recommend not passing in a Scanner and just new one up in the method.

2021-03-26 22:11 UTC, imapcgeek commented on Company.java
> +        userInput = userInput.toLowerCase();
Consider combining into a single line and change variable to isHourlyYN.

2021-03-26 22:11 UTC, imapcgeek commented on Hourly.java
> +    public void changeHours(int newHours);
I recommend changing this to "setHours()"

2021-03-29 21:12 UTC, pcgeek2301 commented on AdministrativeAssistant.java
> +    }
I named it that only because of teacher instruction

2021-03-29 21:16 UTC, pcgeek2301 commented on AdministrativeAssistant.java
> +    }
I had some confusing teacher directions, I will look back at the instructions to verify

2021-03-29 21:22 UTC, pcgeek2301 commented on Company.java
> +    public static void PromptUserForNewEmployee(Company comp, Scanner scnr) {
The scanner would not work if I did not pass it in, I fixed the static methods though

2021-03-31 17:23 UTC, merged